name: Weekly KvScraper
  on: [push, workflow_dispatch]
  jobs:
    scrape:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - run: |
            pip install playwright
            playwright install-deps
            playwright install chromium
            python main.py
